variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GOOGLE_TAG: eu.gcr.io/papers-kubernetes/tezos-synapse:$CI_COMMIT_SHA
  GOOGLE_TAG_LATEST: eu.gcr.io/papers-kubernetes/tezos-synapse:latest
image: tmaier/docker-compose:latest

stages:
  - build
  - publish
  - deploy

build:
  stage: build
  script:
    - docker build -t $GOOGLE_TAG .
  tags:
    - docker

publish:
  stage: publish
  image: google/cloud-sdk
  before_script:
    - echo $GCLOUD_GOOGLE_KEY > key.json
    - gcloud auth activate-service-account $GCLOUD_ACCOUNT --key-file key.json
    - gcloud config set account $GCLOUD_ACCOUNT
    - gcloud config set compute/zone $GCLOUD_ZONE
    - gcloud config set project $GCLOUD_PROJECT
    - gcloud auth configure-docker
  script:
    - docker tag $GOOGLE_TAG $GOOGLE_TAG_LATEST
    - docker push $GOOGLE_TAG
    - docker push $GOOGLE_TAG_LATEST
  only:
    - master
    - development
  tags:
    - docker

k8s-deploy-production:
  stage: deploy
  only:
    - master
  when: manual
  image: google/cloud-sdk
  before_script:
    - echo $GCLOUD_GOOGLE_KEY > key.json
    - gcloud auth activate-service-account $GCLOUD_ACCOUNT --key-file key.json
    - gcloud config set account $GCLOUD_ACCOUNT
    - gcloud config set project $GCLOUD_PROJECT
    - gcloud config set compute/zone europe-west6-a
    - gcloud container clusters get-credentials papers-cluster-production
  script:
    - sed -i "s|_TO_BE_REPLACED_BY_IMAGE_TAG_|"$GOOGLE_TAG"|g" k8s/common/synapse/deployment.yaml
    - kubectl apply -f ./k8s/common/namespace.yaml
    - kubectl apply -f ./k8s/common/ --recursive
    - kubectl apply -f ./k8s/production/ --recursive
  
  tags:
    - docker
