variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKERHUB_TAG: airgapdocker/tezos-synapse:$CI_COMMIT_SHA
  DOCKERHUB_TAG_LATEST: airgapdocker/tezos-synapse:latest
image: tmaier/docker-compose:latest

stages:
  - build
  - publish
  - deploy

build:
  stage: build
  script:
    - docker build -t $DOCKERHUB_TAG ./docker/
  tags:
    - docker

publish:
  stage: publish
  image: google/cloud-sdk
  before_script:
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"
  script:
    - docker tag $DOCKERHUB_TAG $DOCKERHUB_TAG_LATEST
    - docker push $DOCKERHUB_TAG
    - docker push $DOCKERHUB_TAG_LATEST
  only:
    - master
    - development
  tags:
    - docker

k8s-deploy-production:
  stage: deploy
  only:
    - master
  when: manual
  image: google/cloud-sdk
  before_script:
    - echo $GCLOUD_GOOGLE_KEY > key.json
    - gcloud auth activate-service-account $GCLOUD_ACCOUNT --key-file key.json
    - gcloud config set account $GCLOUD_ACCOUNT
    - gcloud config set project $GCLOUD_PROJECT
    - gcloud config set compute/zone europe-west6-a
    - gcloud container clusters get-credentials papers-cluster-production
  script:
    - sed -i "s|_TO_BE_REPLACED_BY_IMAGE_TAG_|"$DOCKERHUB_TAG"|g" k8s/common/synapse/deployment.yaml
    - kubectl apply -f ./k8s/common/namespace.yaml
    - kubectl apply -f ./k8s/common/ --recursive
    - kubectl apply -f ./k8s/production/ --recursive
  
  tags:
    - docker
