worker_app: synapse.app.generic_worker
worker_name: worker10

# The replication listener on the main synapse process.
worker_replication_host: 127.0.0.1
worker_replication_http_port: 9093

worker_listeners:
  - type: http
    port: 8092
    resources:
      - names:
          - client
          - federation

worker_pid_file: /config/worker10.pid
