worker_app: synapse.app.generic_worker
worker_name: worker2

worker_listeners:
 - type: http
   port: 8084
   x_forwarded: true
   resources:
     - names: [client, federation]

worker_pid_file: /config/worker2.pid
