worker_app: synapse.app.generic_worker
worker_name: worker3

worker_listeners:
 - type: http
   port: 8085
   x_forwarded: true
   resources:
     - names: [client, federation]

worker_pid_file: /config/worker3.pid
