apiVersion: v1
kind: LimitRange
metadata:
  name: beacon-node
  namespace: beacon-node
spec:
  limits:
    - default:
        cpu: "0.5"
        memory: "1000Mi"
      defaultRequest:
        cpu: "0.05"
        memory: 150Mi
      type: Container
