apiVersion: v1
kind: LimitRange
metadata:
  name: tezos-matrix
  namespace: tezos-matrix
spec:
  limits:
  - default:
      cpu: '0.5'
      memory: '1000Mi'
    defaultRequest:
      cpu: '0.001'
      memory: 150Mi
    type: Container
