version: "3.5"

services:
  postgres:
    image: postgres:12.0
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=synapsepassword
      - POSTGRES_DB=synapse
  tezos-synapse:
    image: airgapdocker/beacon-node:latest
    depends_on:
      - postgres
    ports:
      - "8008:8008" # 8008 is exposed. Route all traffic from port 443 and 8448 to this port
    environment:
      - DB_HOST=postgres
      - DB_USER=synapse
      - DB_PASS=synapsepassword
      - DB_NAME=synapse
      - SERVER_NAME=matrix.papers.tech
    volumes:
      - ./data/synapse-config:/data
