version: "3.5"

services:
  postgres:
    image: postgres:12.0
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=synapsepassword
      - POSTGRES_DB=synapse
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.4-buster
    expose: 
      - "6379"
  tezos-synapse:
    image: beacon-node
    depends_on:
      - postgres
    ports:
      - "8008:8008" # 8008 is exposed. Route all traffic from port 443 and 8448 to this port
      - "8083:8083" # exposing the workers for loadbalancing
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
    environment:
      - DB_HOST=postgres
      - DB_USER=synapse
      - DB_PASS=synapsepassword
      - DB_NAME=synapse
      - SERVER_NAME=matrix.papers.tech
    volumes:
      - ./data/synapse-config:/data
