apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-dev-1-pvc
  namespace: beacon-node
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
