apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-pvc
  namespace: tezos-matrix
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 1Gi
  storageClassName: standard

