apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: synapse
  namespace: tezos-matrix
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - matrix.papers.tech
        - matrix.prod.gke.papers.tech
      secretName: matrix-synapse-prod-tls  
  rules:
  - host: matrix.papers.tech
    http:
      paths:
        - backend:
            serviceName: synapse-service
            servicePort: 8008
  - host: matrix.prod.gke.papers.tech
    http:
      paths:
        - backend:
            serviceName: synapse-service
            servicePort: 8008
